// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFj_zdN3IctmGLMWlrFprSR9aTUJk0Xqk',
    appId: '1:521976219913:web:afb75aedda726d625c2bd8',
    messagingSenderId: '521976219913',
    projectId: 'cinefile-6252a',
    authDomain: 'cinefile-6252a.firebaseapp.com',
    storageBucket: 'cinefile-6252a.firebasestorage.app',
    measurementId: 'G-BWZ95VSP0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfU-pfnqXjruyq6LLvURNmxgJ_pgKUJxs',
    appId: '1:521976219913:android:5ef07c53c5678a4f5c2bd8',
    messagingSenderId: '521976219913',
    projectId: 'cinefile-6252a',
    storageBucket: 'cinefile-6252a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDidO55Gl0-lXRvwtMOaa5fLhkcj0Q9UUI',
    appId: '1:521976219913:ios:80dc42d83c82ccae5c2bd8',
    messagingSenderId: '521976219913',
    projectId: 'cinefile-6252a',
    storageBucket: 'cinefile-6252a.firebasestorage.app',
    iosBundleId: 'com.alp3r.filmdizi.filmdizi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFj_zdN3IctmGLMWlrFprSR9aTUJk0Xqk',
    appId: '1:521976219913:web:c31614c965695e115c2bd8',
    messagingSenderId: '521976219913',
    projectId: 'cinefile-6252a',
    authDomain: 'cinefile-6252a.firebaseapp.com',
    storageBucket: 'cinefile-6252a.firebasestorage.app',
    measurementId: 'G-BZY1VGZ7NY',
  );
}
